### PR TITLE
Add checks for array length before `aref`ing

### PR DESCRIPTION
**Pull request by narendraj9**
I need to change this manually after every new installation so I thought it makes sense to suggest these changes to the repository directly. Thanks! :)

### CODE REVIEW

**Comment by narendraj9** [comment]
I don't know much about what to expect in `info` so I just chose to make sure that all `aref`s are checked for the `index` we use. `(aref info 1)` fails if the length is not equal or greater than `2`.

**Comment by stardiviner** [comment]
This function is used to check the misspelled, and give out suggestions. If empty like empty vector, then no suggestion. If I understand correctly. So checking it is empty is fine.

**Comment by narendraj9** [comment]
Okay, that makes sense. Thanks! :)

**Comment by stardiviner** [comment]
This is fixed in https://github.com/atykhonov/google-translate/pull/109

**Pull request closed without merging**
