### PR TITLE
Add CI test

### PR DESCRIPTION
**Pull request by stardiviner**
Try to add CI test for this project.

Don't know how to test whether it works.

### CODE REVIEW

**Comment by atykhonov** [comment]
Great!

> Don't know how to test whether it works.

I don't understand neither. It should have been started automatically in this PR (because there is `on: [push, pull_request]`). And we could see that it is running... and the results as well. But here are no any signs of the executed job. Well, I need to investigate more. I'll try to do this during the weekends.

P.S. Thanks for review request.

**Comment by atykhonov** [comment]
@stardiviner please try again, just commit any change to this branch.

**Comment by stardiviner** [comment]
Ok, seems working now.

**Comment by atykhonov** [comment]
@stardiviner I sent you reply by email and sent some comments regarding the PRs.

**Comment by stardiviner** [comment]
The CI works fine now after I update workflow file.

**Pull request merged**
